tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-fonts"
tap "homebrew/cask-versions"
tap "homebrew/core"
brew "bash"
brew "cdrtools"
brew "coreutils"
brew "cvs"
brew "dhex"
brew "dmg2img"
brew "duti"
brew "opus"
brew "tesseract"
brew "ffmpeg"
brew "findutils"
brew "gcc"
brew "git"
brew "gnu-sed"
brew "gzip"
brew "htop"
brew "iftop"
brew "imagemagick"
brew "lftp"
brew "macvim"
brew "mas"
brew "midnight-commander"
brew "ncdu"
brew "neovim"
brew "nmap"
brew "ocrmypdf"
brew "p7zip"
brew "par"
brew "poppler"
brew "pdfsandwich"
brew "pdftk-java"
brew "reattach-to-user-namespace"
brew "rsync"
brew "squashfs"
brew "tcpdump"
brew "tesseract-lang"
brew "tmate"
brew "tmux"
brew "unzip"
brew "wget"
brew "xorriso"
cask "adobe-acrobat-reader"
cask "adoptopenjdk8"
cask "android-file-transfer"
cask "android-platform-tools"
cask "arduino"
cask "cyberduck"
cask "firefox"
cask "font-source-code-pro-for-powerline"
cask "gimp"
cask "gitkraken"
cask "google-chrome"
cask "handbrake"
cask "hex-fiend"
cask "inkscape"
cask "iterm2"
cask "itsycal"
cask "keka"
cask "libreoffice"
cask "libreoffice-language-pack"
cask "meld"
cask "menumeters"
cask "microsoft-auto-update"
cask "microsoft-office"
cask "noti"
cask "openvpn-connect"
cask "openzfs"
cask "pdfsam-basic"
cask "platypus"
cask "rectangle"
cask "skype"
cask "timemachineeditor"
cask "virtualbox"
cask "virtualbox-extension-pack"
cask "visual-studio-code"
cask "vlc"
cask "xquartz"
cask "zoom"
mas "AJA System Test Lite", id: 1092006274
mas "Amphetamine", id: 937984704
mas "GarageBand", id: 682658836
mas "Image2icon", id: 992115977
mas "iMovie", id: 408981434
mas "Keynote", id: 409183694
mas "Microsoft Remote Desktop", id: 715768417
mas "NordVPN IKE", id: 1116599239
mas "Numbers", id: 409203825
mas "Pages", id: 409201541
mas "Photos Duplicate Cleaner", id: 592704001
mas "Surfshark", id: 1437809329
