#!/bin/sh
#
# Filename: config-debian-preseed-geoscope
# Author: Olivier Sirol <czo@free.fr>
# License: GPL-2.0 (http://www.gnu.org/copyleft)
# File Created: 12 April 2018
# Last Modified: Sunday 05 April 2026, 12:30
# $Id: config-debian-preseed-geoscope,v 1.41 2026/04/05 10:31:04 czo Exp $
# Edit Time: 11:09:08
# Description:
#
#            debian 10 preseed geoscope update
#
# keyboard:
#  apt-get install keyboard-configuration
#  dpkg-reconfigure keyboard-configuration
#  service keyboard-setup restart
# locales:
#  dpkg-reconfigure locales
# time-zone:
#  dpkg-reconfigure tzdata
# upgrade:
#  dpkg-reconfigure unattended-upgrades
#   /etc/apt/apt.conf.d/20auto-upgrades
#   /etc/apt/listchanges.conf
#
# aptitude search '~i ~Osalt'
#
# Copyright: (C) 2018-2026 Olivier Sirol <czo@free.fr>

LOGFILE="/tmp/debian_preseed_up_root_$(date '+%Y-%m-%d_%H-%M')_$$.log"

(
export LANG=C
export QUIET="-q -y"
export DEBIAN_FRONTEND=noninteractive
##export DEBIAN_PRIORITY=critical

echo $(date +%Y-%m-%d) > /etc/lsb-czo-installdate
echo $(date +%Y-%m-%d) > /etc/lsb-czo-updatedate

# echo "##====================================================================##"
# echo "-> apt sources/update"

# echo "postfix postfix/main_mailer_type select Satellite system
# postfix postfix/root_address string geoscope-alert@ipgp.fr
# postfix postfix/mailname string ipgp.fr
# postfix postfix/relayhost string smtp.ipgp.fr" | debconf-set-selections

# perl -i -pe 's, main contrib non-free, main,' /etc/apt/sources.list
# perl -i -pe 's, main non-free contrib, main,' /etc/apt/sources.list
# perl -i -pe 's, main, main contrib non-free,' /etc/apt/sources.list

# apt-get $QUIET update
# apt-get $QUIET upgrade
# apt-get $QUIET dist-upgrade
# apt-get $QUIET clean

# apt-get $QUIET install aptitude debconf-utils debootstrap lsb-release bash bash-completion ssh rsync vim-athena xsel xclip xauth ncdu htop iftop iotop iptraf mc screen tmux tmate zsh zsh-doc perl-doc nmap tcpdump wget curl lftp rcs cvs git git-restore-mtime exuberant-ctags sqlite3 hexcurse colordiff perltidy picocom bc command-not-found recode iperf libnet-xmpp-perl libpar-packer-perl libterm-readline-gnu-perl moreutils p7zip p7zip-full zstd mlocate sysstat strace parted gpart gdisk kpartx ethtool telnet tree ntpdate dnsutils munin-node autofs nfs-client postfix bsd-mailx libarchive-tools qemu-guest-agent


echo "##====================================================================##"
echo "-> sshd"

perl -i -pe 's,^#?PermitRootLogin.*,PermitRootLogin yes,' /etc/ssh/sshd_config
systemctl restart sshd


echo "##====================================================================##"
echo "-> dpkg-reconfigure tzdata"

ln -fs /usr/share/zoneinfo/Etc/UTC /etc/localtime
#ln -fs /usr/share/zoneinfo/Europe/Paris /etc/localtime
dpkg-reconfigure -f noninteractive tzdata


echo "##====================================================================##"
echo "-> dpkg-reconfigure locales"

perl -i -pe 's,# en_US.UTF-8 UTF-8,en_US.UTF-8 UTF-8,' /etc/locale.gen
perl -i -pe 's,# fr_FR.UTF-8 UTF-8,fr_FR.UTF-8 UTF-8,' /etc/locale.gen
update-locale LANG=en_US.UTF-8
locale-gen


echo "##====================================================================##"
echo "-> autofs"

perl -i -pe 's,^#/net\s*-hosts.*,/net    -hosts,' /etc/auto.master
systemctl restart autofs


echo "##====================================================================##"
echo "-> NTP"
# timesyncd in >= 10

cat << 'EOF' > /etc/ntp.conf
# /etc/ntp.conf, configuration for ntpd; see ntp.conf(5) for help
# czo, 2010-03-04

driftfile /var/lib/ntp/ntp.drift
leapfile /usr/share/zoneinfo/leap-seconds.list
statistics loopstats peerstats clockstats
filegen loopstats file loopstats type day enable
filegen peerstats file peerstats type day enable
filegen clockstats file clockstats type day enable
restrict -4 default kod notrap nomodify nopeer noquery limited
restrict -6 default kod notrap nomodify nopeer noquery limited
restrict 127.0.0.1
restrict ::1
restrict source notrap nomodify noquery

# CHEZWAM
#server 192.168.11.1

# IPGP
server 10.0.21.15
server 10.0.21.16
server 10.0.21.17

## Lognes
# pool 0.fr.pool.ntp.org iburst
# pool 1.fr.pool.ntp.org iburst
# pool 2.fr.pool.ntp.org iburst
# pool 3.fr.pool.ntp.org iburst

## et World Pool
# pool 0.debian.pool.ntp.org iburst
# pool 1.debian.pool.ntp.org iburst
# pool 2.debian.pool.ntp.org iburst
# pool 3.debian.pool.ntp.org iburst

EOF
systemctl restart ntp
ntpq -p


echo "##====================================================================##"
echo "-> timesyncd"
## ntp in debian 9

#cp /etc/systemd/timesyncd.conf /etc/systemd/timesyncd.conf.czorig
cat << 'EOF' > /etc/systemd/timesyncd.conf
# See timesyncd.conf(5) for details.
# 2020/10/14 : Modified by Olivier Sirol <czo@free.fr>

[Time]
# IPGP
NTP=10.0.21.15 10.0.21.16 10.0.21.17
# chez wam
#NTP=192.168.11.1

FallbackNTPServers=0.fr.pool.ntp.org 0.pool.ntp.org 1.pool.ntp.org 2.pool.ntp.org

EOF
systemctl restart systemd-timesyncd.service
timedatectl show-timesync --all


echo "##====================================================================##"
echo "-> munin"

perl -i -pe 's,^host_name localhost.localdomain,#host_name localhost.localdomain,' /etc/munin/munin-node.conf
perl -i -pe 's,^allow \^10\\.2\\.5\\.10\$\n,,' /etc/munin/munin-node.conf
perl -i -pe 's,^allow \^10\\.1\\.6\\.16\$\n,,' /etc/munin/munin-node.conf
perl -i -pe 's,^allow \^127\\.0\\.0\\.1.*,allow \^127\\.0\\.0\\.1\$\nallow \^10\\.2\\.5\\.10\$\nallow \^10\\.1\\.6\\.16\$,' /etc/munin/munin-node.conf
service munin-node restart


echo "##====================================================================##"
echo "-> cron czo-email-at-reboot"
# GPADM:  geomag/paleomag admin
# ADMIN:  ChezWam admin
# GSADM:  geoscope admin
# SMVADM: svm admin

cat << 'EOF' > /etc/cron.d/czo-email-at-reboot
# Filename: czo-email-at-reboot
@reboot      root   SUJ="[GSADM] REBOOT `hostname` at `date`" ; ( echo $SUJ ; date ; uname -a ) | mail -s "$SUJ" root > /dev/null
EOF
chmod 644 /etc/cron.d/czo-email-at-reboot


echo "##====================================================================##"
echo "-> cron czo-motd-czolsb"

cat << 'EOF' > /etc/cron.d/czo-motd-czolsb
# Filename: czo-email-at-reboot
@reboot      root   /etc/czolsb > /etc/motd 2> /dev/null
EOF
chmod 644 /etc/cron.d/czo-motd-czolsb


echo "##====================================================================##"
echo "-> fixup postfix"

## pb postfix in debian10?
mkfifo /var/spool/postfix/public/pickup


echo "##====================================================================##"
echo "-> bsd-mailx aliases"

## mailutils don't aliases root in debian12... so bsd-mailx >= debian12
perl -i -pe 's,^alias root.*\n,,' /etc/mail.rc
echo "alias root geoscope-alert@ipgp.fr" >> /etc/mail.rc


echo "##====================================================================##"
echo "-> systemctl enable/disable"

systemctl disable openipmi.service
systemctl enable serial-getty@ttyS0.service
systemctl start serial-getty@ttyS0.service


echo "##====================================================================##"
echo "-> config files"

cd /root
curl -fsSL https://raw.githubusercontent.com/czodroid/dotfiles/master/config-fast-copy | sh

cd /root
cp -rp .ssh .ssh_fast_$(date +%Y-%m-%d)_$$
rm -fr .ssh
mkdir .ssh
chmod 700 .ssh

#ssh-keygen -t rsa -N "" -f .ssh/id_rsa
ssh-keygen -t rsa -b 4096 -N "" -f .ssh/id_rsa

# new passphrase:
#ssh-keygen -p -f id_rsa

cat << 'EOF' >> .ssh/config
# Filename: config

##=======================================================================##
## THE REMAINDER

Host *
 ## new 2014-2015
 # Ciphers aes128-ctr,aes192-ctr,aes256-ctr,aes128-gcm@openssh.com,aes256-gcm@openssh.com,chacha20-poly1305@openssh.com
 # KexAlgorithms curve25519-sha256
 ## 2005
 Ciphers aes128-ctr,aes192-ctr,aes256-ctr

 NoHostAuthenticationForLocalhost yes
 StrictHostKeyChecking ask
 HashKnownHosts no
 GSSAPIAuthentication no
 ServerAliveInterval 29
 ServerAliveCountMax 3
 ForwardX11 yes
 # AddKeysToAgent yes

EOF

echo "# this host" > .ssh/authorized_keys
cat .ssh/id_rsa.pub  >> .ssh/authorized_keys

cat << 'EOF' >> .ssh/authorized_keys

# GEOSCOPE team
ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQCpuVrKcw0PcSUnOIBz+yaSVObq3oroyFeL1luCgHhHKER7TxhiRFNLYRJpjZHxslaORLVM++Nd+rwWRFnrSGEugfvkQjdL45tnY9IvT1KeMsAotd72DN9oYNy3Nq7XAYvx9obpf71JPyaR0Y2hfx0sKDHn5NHT0mTs3KH66HHybRpCvPI9W6g+TBEIAOFiUY3zoK4D36wDGwR0aZBzDqtfedgwgXKzHCVb8ZNnCqHP/2DVJRgvqQbtX164D/LAFx66qwSqzp2ogTlhHtk2qF34cw+ve30Q7cSHVIraky+innjkTRkMkenSd4Mv1mLyp/ItkQY0cTfxXGttfHYTFGKV1MD0TKWi9ccihrW2+slXWFxbkXG7TGpBNCsYVW7ueCy4Ki8FIREOhiZSoHXza4JjMdR1Xgkn80xgeBnauRL4Dj9RGGLFrbuZFyoUx3gnpw1HkqrmvhhkkuVSzYvU9E8gkfoSm1yL3ALl4vQEtzdPPPd9mMqfaqbRluKIEfx0X2BAS9tWCXZvWiJcQ/UkcHlK6NWYSZp60jGs1VrDVgHtS1p/B4+fB3Tpw2f7Oz5ePG5goybYBCRhOu87rU8xB3ka7XH7p6C/yS7jxYcvaq57INEknZ5P4mQ0BQRqz+/nDBMksIzxHXTDWVGc0hqSJtzKC33JyLKH3fudXJ0TSZQd5w== leroy@leroy-pc
ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQC1pgf7e+gh3Ywe1rxOSqnyaq1sQBnSgRFsiZaAWjovBTK1JltKgzmDY6ipNj/6zv106mugogrIlE1BrWDtqahfMdEkahquBBeSCnRJgm3FcD31UWctwBMdaRRrgJU1oFkzx5ECu9vqokCBFnIEF6UZb4spJ9PEjJEnyFJ6t8lvSoVeQ42iW6Og/5B/6f2O60XEMcqo1reRGEAV+znkYC42kS9ZsgZCIznram28RKmN+k5T0vN849kXBQCnMrCOm031IUNsiQbLkUKgEhbiRbaUB4S5sAtnEpVtqILcVCy0CyfPLhspUzN+b74u/bZfay2S3yoGBMqeIw8fN1nY20XSz8TqcuDNtLGHmICyRxnNiV08Y6fhya6ajIjl1nVxCkoo0g7/RkDdqr7YGUdc+HiVY36hqtaFDTWIHT1H1BGScdhfME8IN3e8uHD3WPlKuhBhuFJuMdZiia3k70sl1D5XcFoVQiRckNk5YObDyk75aZ7PbybhXxMD3tzBofQzpPnHbfsnBTZFLFpQHlm63wEjojqoxd24BgRE8JGZE9dTo+1CFmzmvHYyZp9bg44fL3LGnDXtdn1z9CjRx3Y+spiCbXKYCQSFmPocoBS6pHQGO6wfwBf7RmFHbBq6WYsNzyFwfQsbvC7yJNlFrJznkkB81s4ZFB+NQfrzOdfQB/S18w== czo@bunnahabhain
ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDnHUkqDCfD3ifnVKoEEbbewTY5PF7IEhgelt32luNk0ypKLQEn5JIe4JN3A1jFsLM1vPmUGNms/2/Q83LK6V7v54Y0BLeyGHiCxa9c4uA8fg7VNqSvgiWdU7gn21whcc2OK3bNK45MYSQjlo7Ft8eui6oYvf2yK2mYrpFz3xKOYg7Y3NcU46KHmEoC6oDx2q8RZO4uCUnCrlXQdt7cks183DgAg8UfluWHT1W7y/tQp7dHGcgXgaXuHeoc3HK5JoC15QIaIbgYmAmA671watlpE6EFQy1oryx39Au8ot60O98Rpxo4m4vtE8LS9uWMFAYA6+kvR3B6SvLiWyij+C3uT2kPfEtEmwQ5yrAwflYUkxbklVTYFt6LdD/AP2HxPPuVF3lq5SEGrnVjD+TD93TI9ZyBWt07nYQdJLVvdm+a6bBVLEAo4jgd/E8VOxReJnfakg1wwvP52BhlO0uJZk9SWnJvoSFZcZTSvT4ZmJYoRspVORTjomDCZI5RFMLpeCJ8hf+6V3NUnRdtphvS8Kkm3VQwPzwPgnIeLb58Ss+dGySV+efd9AXCul1sfeJwnEX0kKqpnP4a61uf8a/BmrJU+CQyacy9f7HScgqm0iilwzAT2ovRF1mvcJbFxFYiLURB24cgalVTbSdZm/CMTwUiNRJ1K7E1A4f7/L80ZGH8Jw== celeste@george

# backup
ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQCszxXrx25w8pM34DZ2mK1ugETzzeZ+RDVpDd7lwURM330z9FjAebXqxO/U8FXCMsPwY2KN5lyS9wVafwdQBO2tlWxpHLAh/ZopjFFFAFsEjZXupgqsRF8uHFMYgJs7JLgDz0OFwcmGV8+Zcm6vvGxRTmMlEwqkhllVDk9N/yOGFYrtQ2mOWCmKmmlujK11hNIMzMk/PJvgtPqI+ML+z26P3z9fWNIfiHnGuRUq90f18IUjJnYLBDsKEbHfLDrYR4Hgplpv0ReEBltCxppyp72g1ILc+iAC0zYts5bGP3m59KMz0onCHUG/buP/qGXg7lQdalAHdjk58ijtPQEx3aXk5eoL4Wn94JFVGrUiL3j+sOu+PCQdepRYHDbh1LmSKc3XV2yc2xZf+LqDS4QpI0ZgkW7O6TH/5cO61+cQLMiZfp35yOCAD52TrXdupBS9b84NfuJo674Are5qzZ07sVHP96s2tsHcNIxJFukjW+Tj3QFTJxuFgtomJdfRxqD2Y9Od9caMWPdB950Jj1hwf+FA2JuZ9y0skr+DWuGS01ty23xwS0PLDMC707xw2+qFun/iEH4MvAqfstIwAVTdUMjB2red5L07NiGstlnSADMyQOVJdNtTd1K5WgAjDXvA0N/91xCvcZDtHcO7qb64cM/RVl+dcQq5w8SpO1wzUq8KiQ== root@bigfish
ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQCxcaXJWMUucnrYd3oRWLZ1e/ur4knE1KeKXXYiwr3u9yVXepKTVLEnzSP0pvkzSqelXbVGzSmCxOMdvX8LjnBEOdGddnWBbi1AAVVfYMm6+PWag92cjwcgHB7Nx6DQbAxX8d4ke2B2Tk8P4btqNCFRcKwjZo02KoZINassOWn7f03cc8xlqfqCtUoFAKPcliF3EFppmYw/8CWBgvQL8PcPnxDKiPTO4L4cLK8e4tCg0UKzr1dr8dpTkCXg9REjuGqfIpRAbERzVqg8l266eRn/nlsaWSU9sPH5rY9B0R314QaJNGTfmRoOlj9U4CQBSLA3P5gf0klyK/LR1Xc7XTQYe4X4qrShQa3OmzZBv87MBz2mEF7hstXMigUtjfqkVSKbygiwdlfAa3GQUpNzLZWxj2gAXR1KLdVFx9IGOL7D6TQy2XymUfO3iS6hoBRGnmbbiVY/aXGdLjKOkSNahtUZvPJTc6yrLSGNAjzxr1IVzv6IJlsbwR/YeznDvTa4/OldM2dbfKtG6I5moEF/4wSqzye9UPdZdW7fZURGz9aSixntX5GKJj1L/3aHAGNCa2IOfxR8cwp0qb6YbWFbUUmz+dtdSFhDgD01V4Gwes441an9sP30CC4l9QXwm7M6B0w1Fu7J4Jk+2SOjGgii17VcJ0AQ7LvCs/c/51sGDXyl0Q== root@bunnahabhain

# munin-node on this host from geoscopemunin or smv-munin
from="10.2.5.10,10.1.6.16",command="/bin/false",no-pty,no-X11-forwarding,no-agent-forwarding,permitopen="localhost:4949" ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQC7n6r8dyTMqrC0HdlbNOrb48GXdhYwkp0Vd+nnf4nMeTCDYwyO9Kr7pjtqGuJKmapZAFvOivT8aCuwIk4arCHkamk5SCRNCIPnk8grK7Hhd9zQs00ro7oO44ORroeDB+wdlWqvrwxTk1ppRsO6iKksCPjpDkJSaiXGatv+xVdGNI2D2PysgZcvDXVxNzUxYiaYZibVnjZ+AN6v+g2Brs7YRWfxlxE7WCdrPUyAuxpOEbvMbXuSd2VEGwUAaXvJnoZnLRyzfvmBv+MgWCSivADi1XRbhMDtTxo/9mBugOZb1brAleIwu9wJOe/Wfx6iQX8P7LRXwHbdJcUlazVCd4ZFwxpeK9+WCDXSln0NkarH7KkAfP83yjk+Kyw5ejTX0l7GXL+Cwj+7RtbrsEiz1XYBxRScw9rtSD0LjyCdgJkn0k7S2Q3ofSN7KVmxkOKsf79iSt9eGZjGCSdnrRqJclpwPkbzKcN6EqgfpYtddWRo2iKJsy4w7cX0XDhxT6Cg9wAtFuAU5wQh4WExiTRB82I2Oig6RdkDTDaEfO1vxKW/Ddh4e9mYwAbXKhVNMPK2Vi5jHmMW2LD7gVlui99svxOD3M50v3QsQ+NxnQLFpgOAke1kvlVShdEpeVNntaF1HzaOw8mYYuzs/gMubGBoReNR2dn3XXixgyt2J7naakvLjQ== munin

# others

EOF

chmod 600 .ssh/config
chmod 600 .ssh/authorized_keys


echo "##====================================================================##"
echo "-> motd"

/etc/czolsb > /etc/motd


echo "##====================================================================##"
echo "<- end!"
echo
echo "Log file in:"
echo "$LOGFILE"

) 2>&1 | tee $LOGFILE

