#!/bin/sh
#
# Filename: config-fast-copy-lab
# Author: Olivier Sirol <czo@free.fr>
# License: GPL-2.0 (http://www.gnu.org/copyleft)
# File Created: 12 May 1999
# Last Modified: Wednesday 30 August 2023, 21:29
# $Id: config-fast-copy-lab,v 1.2 2023/08/30 19:32:24 czo Exp $
# Edit Time: 6:05:56
# Description:
#
#  copy my config files (you must do a "cd" before running this script)
#   curl -fsSL https://gitlab.com/czo/dotfiles/raw/master/config-fast-copy | sh
#   curl -fsSL https://raw.githubusercontent.com/czodroid/dotfiles/master/config-fast-copy | sh
#
#  test ssl -k:
#   curl -k -fsSLO $GIT/$f
#   wget --no-check-certificate -q $GIT/$f -O $f
#
# Copyright: (C) 1999-2023 Olivier Sirol <czo@free.fr>

## gitlab origin
GIT='https://gitlab.com/czo/dotfiles/raw/master'
## github origin
# GIT='https://raw.githubusercontent.com/czodroid/dotfiles/master'

echo "## -> copy my config files"

mkdir -p .config/htop
mkdir -p .config/mc
chmod 700 .config/mc

for f in .Xresources .bashrc .cshrc .cvsrc .gitconfig .inputrc .profile .screenrc .tmux.conf .vimrc .zshrc .config/htop/htoprc .config/mc/ini .config/mc/panels.ini
do
    echo "   <- $f"
    curl -fsSL $GIT/$f -o $f
done

echo "   <- /etc/czolsb"
curl -fsSL $GIT/czolsb -o /etc/czolsb
chmod 755 /etc/czolsb
