#!/bin/sh
#
# Filename: config-debian-preseed
# Author: Olivier Sirol <czo@free.fr>
# License: GPL-2.0 (http://www.gnu.org/copyleft)
# File Created: 29 August 2020
# Last Modified: Tuesday 11 October 2022, 01:42
# Edit Time: 1:11:15
# Description:
#
#   debian preseed/late_command, single or double quote forbiden in pxe/append
#   wget --no-check-certificate -qO- https://git.io/JkHdk | sh
#
# Copyright: (C) 2020-2022 Olivier Sirol <czo@free.fr>
#
# $Id: config-debian-preseed,v 1.24 2022/10/10 23:53:10 czo Exp $

mkdir -p  .config/htop
mkdir -p  .config/mc
chmod 700 .config/mc

for f in .Xresources .bashrc .cshrc .cvsrc .gitconfig .inputrc .profile .screenrc .tmux.conf .vimrc .zshrc .config/htop/htoprc .config/mc/ini .config/mc/panels.ini
do
  wget --no-check-certificate -q https://raw.githubusercontent.com/czodroid/dotfiles/master/$f -O $f
done

curl -fsSL https://raw.githubusercontent.com/czodroid/dotfiles/master/czolsb -o /etc/czolsb
chmod 755 /etc/czolsb

wget --no-check-certificate -qO- https://raw.githubusercontent.com/czodroid/dotfiles/master/config-fast-ssh  | sh

