#!/bin/sh
#
# Filename: config-debian-preseed-chezwam
# Author: Olivier Sirol <czo@free.fr>
# License: GPL-2.0
# File Created: April 1999
# Last Modified: mardi 06 avril 2021, 21:48
# Edit Time: 7:00:50
# Description:
#
#   configure ssh with my authorized_keys and config
#
#   wget --no-check-certificate -qO- https://git.io/JkHdk | sh
#
# $Id: config-debian-preseed-chezwam,v 1.2 2021/04/06 16:50:00 czo Exp $

(
export LANG=C
export QUIET="-q -y"
export DEBIAN_FRONTEND=noninteractive
##export DEBIAN_PRIORITY=critical

echo $(date +%Y-%m-%d) > /etc/lsb-czo-installdate
echo $(date +%Y%m%d) > /etc/lsb-czo-updatedate

##== change config  ==================================================##

# # apt sources
# perl -i -pe 's, main contrib non-free, main,' /etc/apt/sources.list
# perl -i -pe 's, main non-free contrib, main,' /etc/apt/sources.list
# perl -i -pe 's, main, main contrib non-free,' /etc/apt/sources.list

# sshd
perl -i -pe 's,^#?PermitRootLogin.*,PermitRootLogin yes,' /etc/ssh/sshd_config
systemctl restart sshd

# dpkg-reconfigure tzdata
#ln -fs /usr/share/zoneinfo/Etc/UTC /etc/localtime
ln -fs /usr/share/zoneinfo/Europe/Paris /etc/localtime
dpkg-reconfigure -f noninteractive tzdata

# dpkg-reconfigure locales
perl -i -pe 's,# en_US.UTF-8 UTF-8,en_US.UTF-8 UTF-8,' /etc/locale.gen
perl -i -pe 's,# fr_FR.UTF-8 UTF-8,fr_FR.UTF-8 UTF-8,' /etc/locale.gen
update-locale LANG=en_US.UTF-8

# autofs
perl -i -pe 's,^#/net\s*-hosts.*,/net    -hosts,' /etc/auto.master
systemctl restart autofs

# NTP
cat << 'EOF' > /etc/ntp.conf
# /etc/ntp.conf, configuration for ntpd; see ntp.conf(5) for help
# czo, 2010-03-04

driftfile /var/lib/ntp/ntp.drift
statistics loopstats peerstats clockstats
filegen loopstats file loopstats type day enable
filegen peerstats file peerstats type day enable
filegen clockstats file clockstats type day enable
restrict -4 default kod notrap nomodify nopeer noquery
restrict -6 default kod notrap nomodify nopeer noquery
restrict 127.0.0.1
restrict ::1

# CHEZWAM
server 192.168.11.1

# IPGP
# server 10.0.21.15
# server 10.0.21.16
# server 10.0.21.17

# et POOL
# pool 0.debian.pool.ntp.org iburst
# pool 1.debian.pool.ntp.org iburst
# pool 2.debian.pool.ntp.org iburst
# pool 3.debian.pool.ntp.org iburst

EOF

/etc/init.d/ntp restart

# munin
perl -i -pe 's,^host_name localhost.localdomain,#host_name localhost.localdomain,' /etc/munin/munin-node.conf
perl -i -pe 's,^allow \^192\\.168\\.11\\.28\$\n,,' /etc/munin/munin-node.conf
perl -i -pe 's,^allow \^127\\.0\\.0\\.1.*,allow \^127\\.0\\.0\\.1\$\nallow \^192\\.168\\.11\\.28\$,' /etc/munin/munin-node.conf
service  munin-node restart


# cron czo-email-at-reboot
cat << 'EOF' > /etc/cron.d/czo-email-at-reboot
# Filename: czo-email-at-reboot
# 2011/09/10 : Modified by Olivier Sirol <czo@ipgp.fr>

@reboot      root   SUJ="[GSADM] REBOOT `hostname` at `date`" ; ( echo $SUJ ; date ; uname -a ) | mail -s "$SUJ" root > /dev/null
EOF
chmod 644 /etc/cron.d/czo-email-at-reboot


##== config files  ==================================================##
cd /root
curl -fsSL https://raw.githubusercontent.com/czodroid/dotfiles/master/config-fast-ssh | sh
curl -fsSL https://raw.githubusercontent.com/czodroid/dotfiles/master/config-fast-copy | sh

) > /root/debian_preseed_up_$(date '+%Y-%m-%d_%H-%M')_$$.log 2>&1

