#!/bin/sh
#
# Filename: config-fast-copy
# Author: Olivier Sirol <czo@free.fr>
# License: GPL-2.0 (http://www.gnu.org/copyleft)
# File Created: 12 May 1999
# Last Modified: Friday 10 February 2023, 13:59
# $Id: config-fast-copy,v 1.31 2023/02/10 13:15:50 czo Exp $
# Edit Time: 5:14:25
# Description:
#
#   copy my config files
#   curl -fsSL https://raw.githubusercontent.com/czodroid/dotfiles/master/config-fast-copy | bash
#   test ssl:
#       curl -fsSLO https://raw.githubusercontent.com/czodroid/dotfiles/master/$f
#       curl -k -fsSLO https://raw.githubusercontent.com/czodroid/dotfiles/master/$f
#       wget -q https://raw.githubusercontent.com/czodroid/dotfiles/master/$f -O $f
#       wget --no-check-certificate -q https://raw.githubusercontent.com/czodroid/dotfiles/master/$f -O $f
#
# Copyright: (C) 1999-2023 Olivier Sirol <czo@free.fr>

# you must do a "cd" before running this script

echo "## -> copy my config files"

mkdir -p  .config/htop
mkdir -p  .config/mc
chmod 700 .config/mc

for f in .Xresources .bashrc .cshrc .cvsrc .gitconfig .inputrc .profile .screenrc .tmux.conf .vimrc .zshrc .config/htop/htoprc .config/mc/ini .config/mc/panels.ini
do
  echo "   <- $f"
  curl -fsSL https://raw.githubusercontent.com/czodroid/dotfiles/master/$f -o $f
done

echo "   <- /etc/czolsb"
curl -fsSL https://raw.githubusercontent.com/czodroid/dotfiles/master/czolsb -o /etc/czolsb
chmod 755 /etc/czolsb

