#!/bin/sh
#
# Filename: config-fast-copy-k
# Author: Olivier Sirol <czo@free.fr>
# License: GPL-2.0 (http://www.gnu.org/copyleft)
# File Created: 12 May 1999
# Last Modified: Sunday 11 February 2024, 13:16
# $Id: config-fast-copy-k,v 1.5 2024/02/11 12:54:25 czo Exp $
# Edit Time: 6:12:15
# Description:
#
#  copy my config files (you must do a "cd" before running this script)
#   curl -fsSL https://gitlab.com/czo/dotfiles/raw/master/config-fast-copy | sh
#   curl -fsSL https://raw.githubusercontent.com/czodroid/dotfiles/master/config-fast-copy | bash
#
#  test ssl -k:
#   curl -k -fsSLO $GIT/$f
#   wget --no-check-certificate -q $GIT/$f -O $f
#
# Copyright: (C) 1999-2024 Olivier Sirol <czo@free.fr>

## gitlab origin
# GIT='https://gitlab.com/czo/dotfiles/raw/master'
## github origin
GIT='https://raw.githubusercontent.com/czodroid/dotfiles/master'

echo "## -> copy my config files"

mkdir -p .config/htop
mkdir -p .config/mc
chmod 700 .config/mc

for f in .bashrc .clang-format .cshrc .cvsrc .gitconfig .inputrc .pep8 .perltidyrc .phpcs.xml .prettierrc .profile .screenrc .tmux.conf .vimrc .Xresources .zshrc .config/htop/htoprc .config/mc/ini .config/mc/panels.ini
do
    echo "   <- $f"
    curl -k -fsSL $GIT/$f -o $f
done

echo "   <- /etc/czolsb"
curl -k -fsSL $GIT/czolsb -o /etc/czolsb
chmod 755 /etc/czolsb
