#!/bin/sh
#
# Filename: config-debian-preseed
# Author: Olivier Sirol <czo@free.fr>
# License: GPL-2.0
# File Created: August 2020
# Last Modified: mardi 16 février 2021, 21:24
# Edit Time: 1:00:09
# Description:
#
#   debian preseed/late_command, single or double quote forbiden in pxe/append
#
#   wget --no-check-certificate -qO- https://git.io/JkHdk | sh
#   
#
# $Id: config-debian-preseed,v 1.15 2021/02/16 20:25:54 czo Exp $

mkdir -p  .config/htop
mkdir -p  .config/mc
chmod 700 .config/mc

for f in .Xresources .bashrc .cvsrc .inputrc .profile .screenrc .tmux.conf .vimrc .zshrc czolsb .config/htop/htoprc .config/mc/ini .config/mc/panels.ini
do
  wget --no-check-certificate -q https://raw.githubusercontent.com/czodroid/dotfiles/master/$f -O $f
done
chmod +x czolsb

wget --no-check-certificate -qO- https://raw.githubusercontent.com/czodroid/dotfiles/master/config-fast-ssh  | sh


