#!/bin/sh
#
# Filename: config-debian-preseed-chezwam
# Author: Olivier Sirol <czo@free.fr>
# License: GPL-2.0 (http://www.gnu.org/copyleft)
# File Created: 12 April 2018
# Last Modified: Thursday 23 November 2023, 11:33
# $Id: config-debian-preseed-chezwam,v 1.25 2023/11/23 10:35:36 czo Exp $
# Edit Time: 7:54:19
# Description:
#
#            debian 10 preseed update
#
# keyboard:
#  apt-get install keyboard-configuration
#  dpkg-reconfigure keyboard-configuration
#  service keyboard-setup restart
# locales:
#  dpkg-reconfigure locales
# time-zone:
#  dpkg-reconfigure tzdata
# upgrade:
#  dpkg-reconfigure unattended-upgrades
#   /etc/apt/apt.conf.d/20auto-upgrades
#   /etc/apt/listchanges.conf
#
# aptitude search '~i ~Osalt'
#
# Copyright: (C) 2018-2023 Olivier Sirol <czo@free.fr>

LOGFILE="/tmp/debian_preseed_up_root_$(date '+%Y-%m-%d_%H-%M')_$$.log"

(
export LANG=C
export QUIET="-q -y"
export DEBIAN_FRONTEND=noninteractive
##export DEBIAN_PRIORITY=critical

echo $(date +%Y-%m-%d) > /etc/lsb-czo-installdate
echo $(date +%Y-%m-%d) > /etc/lsb-czo-updatedate

# echo "##== apt sources/update  =============================================##"

# echo "postfix postfix/main_mailer_type select Satellite system
# postfix postfix/root_address string dotslash42+adm@gmail.com
# postfix postfix/mailname string czo.wf
# postfix postfix/relayhost string smtp.free.fr" | debconf-set-selections

# perl -i -pe 's, main contrib non-free, main,' /etc/apt/sources.list
# perl -i -pe 's, main non-free contrib, main,' /etc/apt/sources.list
# perl -i -pe 's, main, main contrib non-free,' /etc/apt/sources.list

# apt-get $QUIET update
# apt-get $QUIET upgrade
# apt-get $QUIET dist-upgrade
# apt-get $QUIET clean

# apt-get $QUIET install aptitude debconf-utils lsb-release bash bash-completion ssh rsync vim-athena xsel xclip xauth ncdu htop iftop iotop iptraf mc screen tmux tmate zsh zsh-doc nmap tcpdump wget curl lftp rcs cvs git ctags recode iperf libnet-xmpp-perl moreutils p7zip zstd mlocate sysstat strace parted gpart gdisk kpartx ethtool dnsutils debootstrap munin-node postfix mailutils autofs nfs-client ntp

echo "##== change config  ==================================================##"


#==============================================
# sshd
perl -i -pe 's,^#?PermitRootLogin.*,PermitRootLogin yes,' /etc/ssh/sshd_config
systemctl restart sshd


#==============================================
# dpkg-reconfigure tzdata
#ln -fs /usr/share/zoneinfo/Etc/UTC /etc/localtime
ln -fs /usr/share/zoneinfo/Europe/Paris /etc/localtime
dpkg-reconfigure -f noninteractive tzdata


#==============================================
# dpkg-reconfigure locales
perl -i -pe 's,# en_US.UTF-8 UTF-8,en_US.UTF-8 UTF-8,' /etc/locale.gen
perl -i -pe 's,# fr_FR.UTF-8 UTF-8,fr_FR.UTF-8 UTF-8,' /etc/locale.gen
update-locale LANG=en_US.UTF-8
locale-gen


#==============================================
# autofs
perl -i -pe 's,^#/net\s*-hosts.*,/net    -hosts,' /etc/auto.master
systemctl restart autofs


#==============================================
# NTP ntpq -p
cat << 'EOF' > /etc/ntp.conf
# /etc/ntp.conf, configuration for ntpd; see ntp.conf(5) for help
# czo, 2010-03-04

driftfile /var/lib/ntp/ntp.drift
leapfile /usr/share/zoneinfo/leap-seconds.list
statistics loopstats peerstats clockstats
filegen loopstats file loopstats type day enable
filegen peerstats file peerstats type day enable
filegen clockstats file clockstats type day enable
restrict -4 default kod notrap nomodify nopeer noquery limited
restrict -6 default kod notrap nomodify nopeer noquery limited
restrict 127.0.0.1
restrict ::1
restrict source notrap nomodify noquery

# CHEZWAM
server 192.168.11.1

# IPGP
# server 10.0.21.15
# server 10.0.21.16
# server 10.0.21.17

# et POOL
# pool 0.debian.pool.ntp.org iburst
# pool 1.debian.pool.ntp.org iburst
# pool 2.debian.pool.ntp.org iburst
# pool 3.debian.pool.ntp.org iburst

EOF
systemctl restart ntp
ntpq -p


#==============================================
## timesyncd que dans 10, dans 9 ntp ?
## timedatectl show-timesync --all

#cp /etc/systemd/timesyncd.conf /etc/systemd/timesyncd.conf.czorig
cat << 'EOF' > /etc/systemd/timesyncd.conf
# See timesyncd.conf(5) for details.
# 2020/10/14 : Modified by Olivier Sirol <czo@free.fr>

[Time]
# IPGP
#NTP=10.0.21.15 10.0.21.16 10.0.21.17
# chez wam
NTP=192.168.11.1

FallbackNTPServers=0.fr.pool.ntp.org 0.pool.ntp.org 1.pool.ntp.org 2.pool.ntp.org

EOF

systemctl restart systemd-timesyncd.service
timedatectl show-timesync --all


#==============================================
# munin CHEZWAM
perl -i -pe 's,^host_name localhost.localdomain,#host_name localhost.localdomain,' /etc/munin/munin-node.conf
perl -i -pe 's,^allow \^192\\.168\\.11\\.28\$\n,,' /etc/munin/munin-node.conf
perl -i -pe 's,^allow \^192\\.168\\.11\\.8\$\n,,' /etc/munin/munin-node.conf
perl -i -pe 's,^allow \^127\\.0\\.0\\.1.*,allow \^127\\.0\\.0\\.1\$\nallow \^192\\.168\\.11\\.8\$,' /etc/munin/munin-node.conf
service  munin-node restart


#==============================================
# cron czo-email-at-reboot
cat << 'EOF' > /etc/cron.d/czo-email-at-reboot
# Filename: czo-email-at-reboot
# 2011/09/10 : Modified by Olivier Sirol <czo@free.fr>

@reboot      root   SUJ="[ADMIN] REBOOT `hostname` at `date`" ; ( echo $SUJ ; date ; uname -a ) | mail -s "$SUJ" root > /dev/null
EOF
chmod 644 /etc/cron.d/czo-email-at-reboot


#==============================================
# cron czo-motd-czolsb
cat << 'EOF' > /etc/cron.d/czo-motd-czolsb
# Filename: czo-email-at-reboot
@reboot      root   /etc/czolsb > /etc/motd 2> /dev/null
EOF
chmod 644 /etc/cron.d/czo-motd-czolsb



echo "##== Email         ==================================================##"
## pb postfix
mkfifo /var/spool/postfix/public/pickup

perl -i -pe 's,^alias root.*\n,,' /etc/mail.rc
echo "alias root root+$HOSTNAME@czo.wf" >> /etc/mail.rc


echo "##== config files  ==================================================##"
cd /root
curl -fsSL https://raw.githubusercontent.com/czodroid/dotfiles/master/config-fast-copy | sh
curl -fsSL https://raw.githubusercontent.com/czodroid/dotfiles/master/config-fast-ssh | sh

echo "##== motd ===========================================================##"
/etc/czolsb > /etc/motd

echo "##== end! ===========================================================##"
echo
echo "Log file in:"
echo "$LOGFILE"

) 2>&1 | tee $LOGFILE

