#!/bin/bash
#
# Filename: czolsb
# Author: Olivier Sirol <czo@free.fr>
# License: GPL-2.0
# File Created: April 2009
# Last Modified: samedi 14 mars 2020, 11:35
# Edit Time: 3:51:40
# Description: 
#   Update LSB tag motd
#   faire rm /etc/lsb-date avant de le lancer
#   par ex : AU && rm /etc/lsb-date && reboot
#   et mettre ce truc dans crond...
#   Faudra aussi mettre /var/www/index.html
#
# $Id: czolsb,v 1.9 2020/03/16 17:27:13 czo Exp $


# do nothing
#exit 0

# ne marche pas dans un cron
rm /etc/lsb-date

export LANG=C

echo "##--------------------------------------------------------------------##"
echo "## -> update lsb-tag motd"

if [ ! -x /usr/bin/lsb_release ]
then
 echo "ERROR: can't find lsb_release"
 exit 1
fi

if [ -f /etc/lsb-date ]
then
 DATE=$(cat /etc/lsb-date)
else
 DATE=$(date +%Y%m%d)
# 20180624
 echo $DATE > /etc/lsb-date
fi

TAG=`echo "$(lsb_release -s -i)_$(lsb_release -s -r)-$(uname -m)-czo-$DATE" | sed 's/\(.*\)/\L\1/'`
# debian_9.4-x86_64-czo-20180624
echo $TAG > /etc/lsb-tag

RELEASE="$(lsb_release -s -i) $(lsb_release -s -r)"
NBCORE=`perl -e '@procn=grep(/^processor\t:/, \`cat /proc/cpuinfo\`); $procn=@procn; print "$procn\n";'`
COREMODEL=`perl -e '($model)= (\`cat /proc/cpuinfo\` =~ /^model name\t: (.*)/m); $model=~ s/  */ /g; print "$model\n";'`
# hack to get total
MEM=$( perl -e  '($mem)= ( qx"cat /proc/meminfo" =~  /^MemTotal:\s*(.*) kB/); $mem=$mem/1024/1024; printf "%.1fGB RAM\n",$mem;' );
SWAP=$( perl -e  '($mem)= (`cat /proc/meminfo` =~  /^SwapTotal:\s*(.*) kB/m); $mem=$mem/1024/1024; printf "%.1fGB SWAP\n",$mem;' );
NAME=$(hostname | cut -d . -f 1)
CNAME=$(uname -m)
KNAME=$(uname -r)

#  4 x Intel(R) Core(TM) i7-4650U CPU @ 1.70GHz - 8GB RAM - 9GB SWAP
#  Linux Debian 9.4 (debian_9.4-x86_64-czo-20180624)
#  kernel x86_64 4.9.0-6-amd64
cat << EOF > /etc/lsb-info
  $NBCORE x $COREMODEL - $MEM - $SWAP
  Linux $RELEASE ($TAG)
  kernel $CNAME $KNAME
EOF

# /etc/lsb-release est fabriqué par ubuntu et resemble a lsb_release -a
# if grep -i 'name.*=.*ubuntu' /etc/os-release > /dev/null; 
# \$(uptime) 

cat << EOF > /etc/motd
              ,,,
             (o o)
####=====oOO==(_)==OOO==============================================####

                         Welcome to $NAME

$(cat /etc/lsb-info)

####================================================================####

EOF

echo "##   <- end"

# ne marche pas dans un cron
cat /etc/motd

exit 0

